default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1   # ⚠️ força IPv4 em vez de ::1
  port: 5432
  username: postgres
  password: 0908
  pool: 5

development:
  <<: *default
  database: sistemas_corporativos_development

test:
  <<: *default
  database: sistemas_corporativos_test

production:
  <<: *default
  database: sistemas_corporativos_production
